import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar></NavBar>

        <main className="h-screen h-max-[700px] place-content-center place-items-center text-lg font-medium">
          {/* //this is works like outlet */}
        {children}
        </main >
        <footer className="text-center bg-amber-500">
          this is awesome component
        </footer>
       
      </body>
    </html>
  );
}
